import { describe, expect, it } from 'vitest'
import { parseGcode } from '~/utils/gcode'

/** Assemble un G-code à partir de ses lignes. */
function gcode(...lines: string[]) {
  return lines.join('\n') + '\n'
}

/** Coordonnées du sommet `i` du résultat, comparées avec tolérance (f32). */
function expectVertex(pos: Float32Array, i: number, [x, y, z]: number[]) {
  expect(pos[i * 3]).toBeCloseTo(x, 4)
  expect(pos[i * 3 + 1]).toBeCloseTo(y, 4)
  expect(pos[i * 3 + 2]).toBeCloseTo(z, 4)
}

/** Coordonnées brutes du sommet `i` (x, y, z). */
function vertex(pos: Float32Array, i: number) {
  return [pos[i * 3], pos[i * 3 + 1], pos[i * 3 + 2]]
}

describe('parseGcode — déplacements', () => {
  it('ne retient que les déplacements qui extrudent', () => {
    const r = parseGcode(
      gcode(
        'G1 X0 Y0 Z0.2 F1800',
        'G1 X10 Y0 E1', // extrusion : segment
        'G0 X20 Y0', // déplacement à vide : ignoré
        'G1 X30 Y0 E2', // extrusion : segment
      ),
    )
    expect(r.segments).toBe(2)
    // Le premier segment part de l'origine…
    expectVertex(r.positions, 0, [0, 0, 0.2])
    expectVertex(r.positions, 1, [10, 0, 0.2])
    // …et le second repart de l'arrivée du déplacement à vide (X20), pas de X10.
    expectVertex(r.positions, 2, [20, 0, 0.2])
    expectVertex(r.positions, 3, [30, 0, 0.2])
  })

  it('ignore la première extrusion sans position de départ connue', () => {
    // Aucun déplacement préalable : on ne connaît pas le point de départ.
    const r = parseGcode(gcode('G1 X10 Y10 E1'))
    expect(r.segments).toBe(0)
  })

  it('gère les nombres négatifs et décimaux', () => {
    const r = parseGcode(gcode('G1 X0 Y0 Z0.2', 'G1 X-1.5 Y2.25 Z0.3 E0.4'))
    expectVertex(r.positions, 1, [-1.5, 2.25, 0.3])
  })

  it('gère les déplacements relatifs (G91)', () => {
    const r = parseGcode(
      gcode('G90', 'G1 X10 Y10 Z0.2', 'G91', 'G1 X5 Y-2 E1', 'G1 X5 Y0 E2'),
    )
    expect(r.segments).toBe(2)
    expectVertex(r.positions, 1, [15, 8, 0.2])
    // Le second déplacement relatif repart de (15, 8).
    expectVertex(r.positions, 2, [15, 8, 0.2])
    expectVertex(r.positions, 3, [20, 8, 0.2])
  })
})

describe('parseGcode — extrusion', () => {
  it('détecte l’extrusion en mode absolu (M82, défaut)', () => {
    const r = parseGcode(gcode('G1 X0 Y0', 'G1 X10 Y0 E1', 'G1 X20 Y0 E1'))
    // Le second déplacement ne consomme pas de filament : pas de segment.
    expect(r.segments).toBe(1)
  })

  it('détecte l’extrusion en mode relatif (M83)', () => {
    const r = parseGcode(
      gcode('M83', 'G1 X0 Y0', 'G1 X10 Y0 E0.5', 'G1 X20 Y0 E0.5'),
    )
    // En relatif, chaque `E` positif compte.
    expect(r.segments).toBe(2)
  })

  it('gère la remise à zéro du filament (G92 E0)', () => {
    const r = parseGcode(
      gcode('M82', 'G1 X0 Y0', 'G1 X10 Y0 E1', 'G92 E0', 'G1 X20 Y0 E1'),
    )
    // Sans le G92, le second `E1` serait vu comme une rétractation.
    expect(r.segments).toBe(2)
  })

  it('tient compte des déplacements de Z seuls (changement de couche)', () => {
    const r = parseGcode(
      gcode('G1 X0 Y0 Z0.2', 'G1 X10 Y0 Z0.2 E1', 'G1 Z0.4', 'G1 X0 Y0 E2'),
    )
    expect(r.layers).toBe(2)
  })
})

describe('parseGcode — lignes ignorées', () => {
  it('ignore commentaires, lignes vides et commandes non pertinentes', () => {
    const r = parseGcode(
      gcode(
        '; generated by a slicer',
        '',
        '   ',
        'M104 S210',
        'G28',
        'G21',
        'G1 X0 Y0 Z0.2',
        'G1 X10 Y0 E1',
        'M117 Impression…',
      ),
    )
    expect(r.segments).toBe(1)
  })

  it('accepte les numéros de commande à plusieurs chiffres (G01)', () => {
    const r = parseGcode(gcode('G01 X0 Y0', 'G01 X10 Y0 E1'))
    expect(r.segments).toBe(1)
  })

  it('renvoie un résultat vide pour un fichier sans extrusion', () => {
    const r = parseGcode(gcode('; rien à imprimer', 'G28', 'G1 X10 Y10'))
    expect(r.segments).toBe(0)
    expect(r.layers).toBe(0)
    expect(r.positions.length).toBe(0)
    expect(r.colors.length).toBe(0)
  })
})

describe('parseGcode — couleurs et bornes', () => {
  it('produit une couleur par sommet (3 canaux, bornés à [0, 1])', () => {
    const r = parseGcode(
      gcode('G1 X0 Y0 Z0', 'G1 X10 Y0 E1', 'G1 Z10', 'G1 X0 Y0 E2'),
    )
    expect(r.segments).toBe(2)
    expect(r.colors.length).toBe(r.segments * 2 * 3)
    for (const c of r.colors) {
      expect(c).toBeGreaterThanOrEqual(0)
      expect(c).toBeLessThanOrEqual(1)
    }
  })

  it('colore la dernière couche plus « chaude » que la première', () => {
    const r = parseGcode(
      gcode('G1 X0 Y0 Z0', 'G1 X10 Y0 E1', 'G1 Z10', 'G1 X0 Y0 E2'),
    )
    // Bas → bleu (beaucoup de bleu, peu de rouge) ; haut → rouge.
    const basRouge = r.colors[0]!
    const hautRouge = r.colors[6]! // 1er sommet du 2e segment
    expect(hautRouge).toBeGreaterThan(basRouge)
  })
})

describe('parseGcode — sous-échantillonnage', () => {
  const lignes = ['G1 X0 Y0']
  for (let i = 1; i <= 10; i++) lignes.push(`G1 X${i} Y0 E${i}`)

  it('conserve tous les segments sous le plafond', () => {
    expect(parseGcode(gcode(...lignes), 100).segments).toBe(10)
  })

  it('réduit au plafond demandé, sans dépasser', () => {
    const r = parseGcode(gcode(...lignes), 4)
    expect(r.segments).toBe(4)
    expect(r.segments).toBeLessThanOrEqual(4)
    expect(r.positions.length).toBe(4 * 6)
  })

  it('garde la géométrie homogène (les deux sommets d’un segment vont ensemble)', () => {
    const r = parseGcode(gcode(...lignes), 5)
    for (let s = 0; s < r.segments; s++) {
      const from = vertex(r.positions, s * 2)
      const to = vertex(r.positions, s * 2 + 1)
      // Sur ces lignes, Y et Z ne bougent jamais.
      expect(from[1]).toBe(0)
      expect(to[1]).toBe(0)
      // Le segment est strictement croissant en X.
      expect(to[0]!).toBeGreaterThan(from[0]!)    }
  })
})
